# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordedaudio',
            old_name='audio_files',
            new_name='audio',
        ),
    ]
